:logfile: ./log/sidekiq.log
:concurrency: 10
staging:
 :concurrency: 10
develop:
 :concurrency: 10
:queues:
 - default
 - mailers
 - critical
 - low

# :concurrency: 10
# :queues:
#   - default
#   - mailers
#   - critical
# :redis:
#   url: redis://localhost:6379/0
#   namespace: sidekiq
# :poll_interval: 10
